const settingsActions = {
    SET_SAVE_SETTINGS_ERROR: 'SET_SAVE_SETTINGS_ERROR',
    CLEAR_SAVE_SETTINGS_ERROR: 'CLEAR_SAVE_SETTINGS_ERROR',
    SET_SAVE_SUCCESS_DISPLAYED: 'SET_SAVE_SUCCESS_DISPLAYED'
};

export default settingsActions;