const authActions = {
    SET_IS_AUTH_FETCHING: 'SET_IS_AUTH_FETCHING',
    GET_AUTH_SAGA: 'GET_AUTH_SAGA',
    SET_AUTH: 'SET_AUTH',
    LOGOUT: 'LOGOUT',
    ADD_STASH_USER_SAGA: 'ADD_STASH_USER_SAGA',
    SET_STASH_USER: 'SET_STASH_USER',
    SET_SNACKBAR: 'SET_SNACKBAR',
    RUN_REFRESH_SAGA: 'RUN_REFRESH_SAGA',
    SET_EXP: 'SET_EXP'
};

export default authActions;