"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var repositoriesActions = {
    GET_FAVORITE_REPOSITORIES_SAGA: 'GET_FAVORITE_REPOSITORIES_SAGA',
    GET_STASH_REPOSITORIES_SAGA: 'GET_STASH_REPOSITORIES_SAGA',
    SET_FAVORITE_REPOSITORIES: 'SET_FAVORITE_REPOSITORIES',
    SET_STASH_REPOSITORIES: 'SET_STASH_REPOSITORIES',
    SEARCH_FAVORITE_REPOSITORIES: 'SEARCH_FAVORITE_REPOSITORIES',
    FILTER_STASH_REPOSITORIES: 'FILTER_STASH_REPOSITORIES',
    DELETE_FAVORITE_REPOSITORY_SAGA: 'DELETE_FAVORITE_REPOSITORY_SAGA',
    ADD_STASH_REPOSITORY_TO_FAVORITES_SAGA: 'ADD_STASH_REPOSITORY_TO_FAVORITES_SAGA',
    REMOVE_STASH_REPOSITORY_FROM_FAVORITES_SAGA: 'REMOVE_STASH_REPOSITORY_FROM_FAVORITES_SAGA',
    SET_IS_REPOSITORIES_FETCHING: 'SET_IS_REPOSITORIES_FETCHING',
    SET_IS_FAVORITE_ONLY: 'SET_IS_FAVORITE_ONLY'
};
exports.default = repositoriesActions;
