"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var developersActions = {
    GET_FAVORITE_DEVELOPERS_SAGA: 'GET_DEVELOPERS_SAGA',
    GET_STASH_DEVELOPERS_SAGA: 'GET_STASH_DEVELOPERS_SAGA',
    SET_FAVORITE_DEVELOPERS: 'SET_FAVORITE_DEVELOPERS',
    SET_STASH_DEVELOPERS: 'SET_STASH_DEVELOPERS',
    SEARCH_FAVORITE_DEVELOPERS: 'SEARCH_FAVORITE_DEVELOPERS',
    FILTER_STASH_DEVELOPERS: 'FILTER_STASH_DEVELOPERS',
    DELETE_FAVORITE_DEVELOPER_SAGA: 'DELETE_DEVELOPER_SAGA',
    ADD_STASH_DEVELOPER_TO_FAVORITES_SAGA: 'ADD_STASH_DEVELOPER_TO_FAVORITES_SAGA',
    SET_IS_DEVELOPERS_FETCHING: 'SET_IS_DEVELOPERS_FETCHING',
    SET_IS_FAVORITE_ONLY: 'SET_IS_FAVORITE_ONLY'
};
exports.default = developersActions;
