const subscribesActions = {
    GET_SUBSCRIBES_SAGA: 'GET_SUBSCRIBES_SAGA',
    SET_SUBSCRIBES: 'SET_SUBSCRIBES',
    SET_SUBSCRIBE_FILTERS: 'SET_SUBSCRIBE_FILTERS',
    TOGGLE_EDITING_WINDOW: 'TOGGLE_EDITING_WINDOW',
    DELETE_SUBSCRIBE_SAGA: 'DELETE_SUBSCRIBE_SAGA'
};

export default subscribesActions;