const subscribesActions = {
    GET_SUBSCRIBES_SAGA: 'GET_SUBSCRIBES_SAGA',
    SET_SUBSCRIBES: 'SET_SUBSCRIBES',
    ADD_SELECTED: 'ADD_SELECTED',
    SET_SUBSCRIBE_FILTERS: 'SET_SUBSCRIBE_FILTERS',
    TOGGLE_EDITING_WINDOW: 'TOGGLE_EDITING_WINDOW',
    DELETE_SUBSCRIBE_SAGA: 'DELETE_SUBSCRIBE_SAGA',
    CREATE_SUBSCRIBE_SAGA: 'CREATE_SUBSCRIBE_SAGA',
    EDIT_SUBSCRIBE: 'EDIT_SUBSCRIBE',
    SAVE_SUBSCRIBE_SAGA: 'SAVE_SUBSCRIBE_SAGA',
    EDIT_SUBSCRIBE_SAGA: 'EDIT_SUBSCRIBE_SAGA',
    SET_SUBSCRIBE: 'SET_SUBSCRIBE',
    TOGGLE_EDITING_REPOSITORY_WINDOW: 'TOGGLE_EDITING_REPOSITORY_WINDOW',
    TOGGLE_EDITING_DEVELOPER_WINDOW: 'TOGGLE_EDITING_DEVELOPER_WINDOW',
    SET_IS_SUCCESS: 'SET_IS_SUCCESS',
    SET_SUBSCRIBE_ERROR: 'SET_SUBSCRIBE_ERROR',
    SET_IS_NEW: 'SET_IS_NEW',
    SET_IS_SUBSCRIBES_FETCHING: 'SET_IS_SUBSCRIBES_FETCHING'
};

export default subscribesActions;