"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.selectSubscribes = function (state) { return state.subscribes.data; };
exports.selectSubscribeFilters = function (state) { return state.subscribes.filters; };
exports.selectIsSubscribeEditing = function (state) { return state.subscribes.isEditing; };
exports.selectIsRepositoryEditing = function (state) { return state.subscribe.isRepositoryPanelDisplayed; };
exports.selectIsDeveloperEditing = function (state) { return state.subscribe.isDeveloperPanelDisplayed; };
exports.selectIsDeveloperValid = function (state) { return state.subscribe.error.developer === ''; };
exports.selectIsRepositoryValid = function (state) { return state.subscribe.error.repository === ''; };
exports.selectDeveloperErrorText = function (state) { return state.subscribe.error.developer; };
exports.selectRepositoryErrorText = function (state) { return state.subscribe.error.repository; };
exports.selectIsSubscribesFetching = function (state) { return state.subscribes.isFetching; };
